# Generated by Django 4.1.5 on 2023-01-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_todoitem_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='text',
            field=models.TextField(default='', null=True),
        ),
    ]
