# Generated by Django 4.1.5 on 2023-01-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0004_list'),
    ]

    operations = [
        migrations.AddField(
            model_name='todoitem',
            name='list',
            field=models.TextField(default=''),
        ),
    ]
